services:
  app:
    build: .
    volumes:
      - ..:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/symfony?serverVersion=15&charset=utf8"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
