controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

post_index:
    path: /post
    controller: App\Controller\PostController::index
    methods: [GET]

post_show:
    path: /post/{post}
    controller: App\Controller\PostController::show
    methods: [GET]

post_store:
    path: /post
    controller: App\Controller\PostController::store
    methods: [POST]

post_update:
    path: /post/{post}
    controller: App\Controller\PostController::update
    methods: [PATCH]